### ISSUE TITLE
OVC_TASKS: Test case for testing "IP conflict check "

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/G8_testing#246]
Cover this issue : 
```
https://github.com/0-complexity/openvcloud/issues/899
```
## scenario 
- Create cs.
- Create vm1 ,vm2.
- Attach external networks to vm1 and vm2.
- Give the vm1 ,vm2 external network it's  ip, and set it up.
- Change default vm1 rout with gateway ip.
- Check that vm1,vm2 can ping google, should succeed.
- Delete Vm2 ext network ip,and give it same ip as vm1.
- Check that Vm2 can't ping google,but vm 1 still can work normally

**Comment by john-kheir** [comment]
This test case need to be implemented with this https://github.com/0-complexity/G8_testing/issues/236
