### ISSUE TITLE
TestCase: Create Rest API testcases for cloudbrocker cloudspace APIs

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/G8_testing#358]
code exist here 
https://github.com/0-complexity/G8_testing/blob/cloudspace/functional_testing/Openvcloud/RESTful/testcases/cloudbroker/test02_cloudspaces.py

**Comment by Dinaamagdy** [comment]
working now on this scenario 
https://github.com/0-complexity/G8_testing/blob/cloudspace/functional_testing/Openvcloud/RESTful/testcases/cloudbroker/test02_cloudspaces.py#L187

**Comment by islamTaha12** [comment]
https://github.com/0-complexity/G8_testing/issues/359
