### ISSUE TITLE
Fix formatting of the class name in the Read the Docs site

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/G8_testing#88]
See: http://85.255.197.77:8080/portal.html#module-functional_testing.Openvcloud.ovc_master_hosted.Portal.testcases.admin_portal.cloud_broker.test01_accounts

Make the class name fit the page and In this case also correct "Cloud brocker" to **Cloud Broker**:

![screen shot 2017-02-03 at 17 24 13](https://cloud.githubusercontent.com/assets/13795109/22599022/a743e5b8-ea35-11e6-938e-bbebd0901ee7.png)

**Comment by ramezsaeed** [comment]
https://0-complexity.github.io/G8_testing/
